export const CANVAS_EVENTS = [
        //Static Canvas events
        "before:render",
        "after:render",
        "canvas:cleared",
        "object:added",
        "object:removed",
        //Canvas events
        "object:modified",
        "object:rotated",
        "object:scaled",
        "object:moved",
        "object:skewed",
        "object:rotating",
        "object:scaling",
        "object:moving",
        "object:skewing",
        "before:transform",
        "before:selection:cleared",
        "selection:cleared",
        "selection:updated",
        "selection:created",
        "path:created",
        "mouse:down",
        "mouse:move",
        "mouse:up",
        "mouse:down:before",
        "mouse:move:before",
        "mouse:up:before",
        "mouse:over",
        "mouse:out",
        "mouse:dblclick",
        "dragover",
        "dragenter",
        "dragleave",
        "drop"
]
